### ISSUE TITLE
on macOS XQuartz

### ISSUE THREAD

**Issue by t-cool** [LdBeth/CLFSWM#1]
Do you think it's possible to run this app on macOS?

```
* (ql:quickload :clfswm)
To load "clfswm":
  Load 1 ASDF system:
    clfswm
; Loading "clfswm"
.Collecting all symbols for Lisp REPL completion... Done.
Updating command list for Shell completion...
ls: /Users/t-cool/.pyenv/bin/*: No such file or directory
ls: authserver: Permission denied
ls: /Applications/Visual: No such file or directory
ls: Code.app/Contents/Resources/app/bin/*: No such file or directory
ls: Studio: No such file or directory
Done. Found 2451 commands in shell PATH.
Updating menus... Done.

(:CLFSWM)

* (in-package :clfswm)

#<PACKAGE "CLFSWM">
* (clfswm:main)

NIL 
NIL 
CLFSWM Error: Name service error in "gethostbyname": 1 (Unknown host).
Reinitializing...
```

**Comment by LdBeth** [comment]
I haven't actually did that, but there might be something useful for you to reference.

https://fanf.livejournal.com/142372.html

<s>Also running CLFSWM from REPL might not be a good idea, since it obviously needs to be running before the default WM (quartz-wm at this case) starts and requires to run `X` solely, which it's a tedious work especially on a machine has window system already running, and no one would like to do that nowadays.</s>

Good luck.

**Comment by LdBeth** [comment]
The good news is, CLFSWM does work with XQuartz.🎉 

The minimal config for this is compiling a `clfswm` executable, and run follow commands in terminal (make sure XQuartz is not running by this time):

```shell
export USERWM=...path/to/clfswm
startx
```

There are a few problems, such as XQuartz doesn't recognize <kbd>Command</kbd> key, but I believe it is not hard to solve. Personally, because of my Japanese layout keyboard works awful under XQuartz and the fact of lacks input methods, I would seldom use X Window under macOS. 😢 

Also XQuartz behaviors slightly different from X.Org for Linux, which makes me reconsider the statement of not to start CLFSWM from a REPL.

<img width="1434" alt="2018-04-22 8 11 42" src="https://user-images.githubusercontent.com/22933696/39105419-9bc52dcc-466a-11e8-9689-63d9006a6ebc.png">
<img width="1348" alt="2018-04-22 8 16 48" src="https://user-images.githubusercontent.com/22933696/39105424-a23b12e8-466a-11e8-9828-409378382dfb.png">

**Comment by t-cool** [comment]
@LdBeth 
Thank you for telling me!
I made it!
<img width="1440" alt="made it" src="https://user-images.githubusercontent.com/3023976/39111301-99f90bd0-470f-11e8-8774-cacc91731b69.png">

I see some errors:

```
$ startx
expr: syntax error
expr: syntax error
expr: syntax error
xauth:  file /Users/t-cool/.serverauth.64900 does not exist
/opt/X11/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
NIL 
NIL 
DEBUG[1 - dbg]  *DISPLAY*=#<XLIB:DISPLAY :0 (The X.Org Foundation R11804000)>   
Screen sizes: ((0 0 1440 878))
Grabbing error: Can't find key 'Menu'
Grabbing error: Can't find key 'Menu'
Grabbing error: Can't find key 'Menu'
```

**Comment by LdBeth** [comment]
Good to hear that.

These errors:

```
font_cache: Scanning user font directories to generate X11 font caches
font_cache: Updating FC cache
font_cache: Done
expr: syntax error
expr: syntax error
expr: syntax error
xauth:  file /Users/ldbeth/.serverauth.6573 does not exist

/opt/X11/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
```

seem unrelated to CLFSWM because calling `startx` with default WM also reproduce that.

```
Grabbing error: Can't find key 'Menu'
```
This one seems to be an issue of `xlib:keysym->keycodes` on macOS.

https://github.com/LdBeth/CLFSWM/blob/cc4153b2cc1d46bd21bc2de980c712798f135b28/src/clfswm-keys.lisp#L155

But more details are welcomed, such as which key press would produce this error message.
